CREATE DATABASE phpmyadmin;
CREATE DATABASE wordpress;
USE mysql;

CREATE USER '$DB_USER'@'%' IDENTIFIED by '$DB_PASS';
CREATE USER '$PMA_USER'@'%' IDENTIFIED by '$PMA_PASS';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON phpmyadmin.* TO '$PMA_USER'@'%' IDENTIFIED BY '$PMA_PASS';
GRANT ALL PRIVILEGES ON wordpress.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';

FLUSH PRIVILEGES;
