version: '3'
services:
  nginx:
    container_name: nginx
    pull_policy: never
    build: 
      context: ./roles/nginx
      dockerfile: Dockerfile
    image: nginx:yassir
    restart: always
    volumes:
      # - /home/ytaousi/cloud-1/data/wordpress:/var/www/html/wordpress
      # - /home/ytaousi/cloud-1/data/phpmyadmin:/var/www/html/phpmyadmin
      - wp-volume:/var/www/html/wordpress
      - pma-volume:/var/www/html/phpmyadmin
    ports:
      - 443:443
      - 80:80
    env_file:
      - .env_variables
    depends_on:
      - mariadb
      - wordpress
  mariadb:
    container_name: mariadb
    build: ./roles/mariadb
    image: mariadb:yassir
    pull_policy: never
    restart: always
    env_file:
      - .env_variables
    volumes:
      # - /home/ytaousi/cloud-1/data/mariadb:/var/lib/mysql
      - db-volume:/var/lib/mysql
  wordpress:
    container_name: php-fpm
    build: ./roles/wordpress_phpmyadmin
    image: php-fpm:yassir
    pull_policy: never
    restart: always
    volumes:
      # - /home/ytaousi/cloud-1/data/wordpress:/var/www/html/wordpress
      - /home/ytaousi/cloud-1/data:/var/www/html/
      - wp-volume:/var/www/html/wordpress
    env_file:
      - .env_variables
    depends_on:
      - mariadb
volumes:
  db-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ytaousi/cloud-1/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ytaousi/cloud-1/data/wordpress
  pma-volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/ytaousi/cloud-1/data/phpmyadmin
