version: '3'
services:
  nginx:
    container_name: nginx
    pull_policy: never
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:yassir
    volumes:
      - ./volumes:/var/lib/nginx/html/
    ports: 
      - 8081:80
#   mariadb:
#     container_name: mariadb
#     build: ./mariadb
#     image: mariadb:yassir
#     pull_policy: never
  wordpress:
    container_name: wordpress
    build: ./wordpress
    image: wordpress:yassir
    pull_policy: never
    volumes:
      - ./volumes/wordpress:/usr/share/wordpress
    # depends_on:
    #   - mariadb
    
