---
- name: configure digital ocean Instance
  import_playbook: ./playbooks/provision.yml
  tags: provision
- name: setup needed folder's
  import_playbook: ./playbooks/folderStructure.yml
  tags: folderStructure
- name: start services
  import_playbook: ./playbooks/startServices.yml
  tags: startServices