version: '3'
services:
  nginx:
    container_name: nginx
    pull_policy: never
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:yassir
    volumes:
      - /home/ytaousi/cloud-1/data/wordpress:/var/www/html/wordpress
      - /home/ytaousi/cloud-1/data/phpmyadmin:/var/www/html/phpmyadmin
    ports:
      - 8443:443
    depends_on:
      - wordpress
  # mariadb:
  #   container_name: mariadb
  #   build: ./mariadb
  #   image: mariadb:yassir
  #   pull_policy: never
  #   env_file:
  #     - .env_variables
  #   volumes:
  #     - /home/ytaousi/cloud-1/data/mariadb:/var/lib/mysql
  wordpress:
    container_name: php-fpm
    build: ./wordpress
    image: php-fpm:yassir
    pull_policy: never
    volumes:
      - /home/ytaousi/cloud-1/data/wordpress:/var/www/html/wordpress
      - /home/ytaousi/cloud-1/data:/var/www/html/
    env_file:
      - .env_variables
    # depends_on:
    #   - mariadb
    
