CREATE DATABASE phpmyadmin;
CREATE DATABASE wordpress;

CREATE USER '' IDENTIFIED by '';
CREATE USER '' IDENTIFIED by '';
GRANT ALL PRIVILEGES ON phpmyadmin.* TO ''@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON wordpress.* TO ''@'%' IDENTIFIED BY '';

FLUSH PRIVILEGES;