version: '3'
services:
  nginx:
    container_name: nginx
    pull_policy: never
    build: 
      context: C:\Users\msi\Desktop\42-Work\cloud-1\srcs\roles\nginx
      dockerfile: Dockerfile
    image: nginx:yassir
    restart: always
    volumes:
      - ./data/wordpress:/var/www/html/wordpress
      - ./data/phpmyadmin:/var/www/html/phpmyadmin
    ports:
      - 8443:443
      - 8080:80
    depends_on:
      - wordpress
  mariadb:
    container_name: mariadb
    build: C:\Users\msi\Desktop\42-Work\cloud-1\srcs\roles\mariadb
    image: mariadb:yassir
    pull_policy: never
    restart: always
    env_file:
      - .env_variables
    volumes:
      - ./data/mariadb:/var/lib/mysql
  wordpress:
    container_name: php-fpm
    build: C:\Users\msi\Desktop\42-Work\cloud-1\srcs\roles\wordpress_phpmyadmin
    image: php-fpm:yassir
    pull_policy: never
    restart: always
    volumes:
      - ./data/wordpress:/var/www/html/wordpress
      - ./data:/var/www/html/
    env_file:
      - .env_variables
    depends_on:
      - mariadb
    