---
- name: Setup DO Instance
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - curl
          - wget
          - dos2unix
          - ca-certificates
          - apt-transport-https
          - gnupg-agent
          - software-properties-common
          - make
          - python3
        state: present
    - name: add gpg keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: update APT repository to add Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
    - name: Install docker-compose
      get_url:
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'